---
#$ sudo yum install -y epel-release
- name: "Install EPEL release"
  yum:
    name: "epel-release"
    state: present

- name: "Prepare odoo install"
  yum:
    name: "{{ item.cle }}"
    state: present
  with_items:
    - "{{ in_odoo.packages }}"

#$ sudo yum-config-manager --add-repo=https://nightly.odoo.com/10.0/nightly/rpm/odoo.repo
- name: "Add repo"
  yum_repository:
    name: "odoo"
    description: "odoo repository"
    baseurl: "https://nightly.odoo.com/10.0/nightly/rpm/"
    gpgkey: "https://nightly.odoo.com/odoo.key"
    gpgcheck: yes

#$ sudo yum install -y odoo
- name: "Install odoo"
  yum:
    name: "odoo"
    state: present

#$ sudo systemctl enable odoo
#$ sudo systemctl start odoo
- name: "Enable odoo"
  systemd:
    name: odoo
    state: started
    enabled: yes

