---
- name: Combinaison des dictionnaires odoo
  set_fact:
    in_odoo: "{{ in_odoo|default({})|combine({item.key : item.value}, recursive=True) }}"
  with_dict: "{{ odoo }}"
  when: odoo is defined
  tags:
    - always

- name: Combinaison des dictionnaires odoo-web
  set_fact:
    in_odoo_web: "{{ in_odoo_web|default({})|combine({item.key : item.value}, recursive=True) }}"
  with_dict: "{{ odoo_web }}"
  when: odoo_web is defined
  tags:
    - always

- name: Combinaison des dictionnaires
  set_fact:
    in_odoo_web: "{{ in_odoo_web|default({})|combine({item.key : item.value}, recursive=True) }}"
  with_dict: "{{ odoo_web }}"
  when: odoo_web is defined
  tags:
    - always

- name: Debug vars odoo
  debug:
    var: "{{ item }}"
  with_items:
    - in_odoo
    - in_odoo_web
  tags:
    - debug
    - always


- name: Installation odoo
  include_tasks: tasks/installation.yml

- name: Configuration odoo
  include_tasks: tasks/configuration.yml
